"""tracks: tracks, steps, enrollments, progress

Revision ID: f58fea393fec
Revises: 8a1f6e2c9d40
Create Date: 2026-06-11 19:32:41.913513+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f58fea393fec'
down_revision: Union[str, None] = '8a1f6e2c9d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_company_id'), 'tracks', ['company_id'], unique=False)
    op.create_index(op.f('ix_tracks_status'), 'tracks', ['status'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('track_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'user_id', name='uq_enrollment_track_user')
    )
    op.create_index(op.f('ix_enrollments_company_id'), 'enrollments', ['company_id'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_enrollments_track_id'), 'enrollments', ['track_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('track_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('track_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('require_quiz', sa.Boolean(), nullable=False),
    sa.Column('pass_score', sa.Float(), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_steps_company_id'), 'track_steps', ['company_id'], unique=False)
    op.create_index(op.f('ix_track_steps_document_id'), 'track_steps', ['document_id'], unique=False)
    op.create_index(op.f('ix_track_steps_track_id'), 'track_steps', ['track_id'], unique=False)
    op.create_table('step_progress',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('enrollment_id', sa.String(length=32), nullable=False),
    sa.Column('step_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['track_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'step_id', name='uq_progress_enrollment_step')
    )
    op.create_index(op.f('ix_step_progress_company_id'), 'step_progress', ['company_id'], unique=False)
    op.create_index(op.f('ix_step_progress_enrollment_id'), 'step_progress', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_step_progress_step_id'), 'step_progress', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_progress_step_id'), table_name='step_progress')
    op.drop_index(op.f('ix_step_progress_enrollment_id'), table_name='step_progress')
    op.drop_index(op.f('ix_step_progress_company_id'), table_name='step_progress')
    op.drop_table('step_progress')
    op.drop_index(op.f('ix_track_steps_track_id'), table_name='track_steps')
    op.drop_index(op.f('ix_track_steps_document_id'), table_name='track_steps')
    op.drop_index(op.f('ix_track_steps_company_id'), table_name='track_steps')
    op.drop_table('track_steps')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_track_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_company_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_tracks_status'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_company_id'), table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
