"""add document_versions.source_uri

Revision ID: 4c97e17b5cff
Revises: dbb5f4b3a360
Create Date: 2026-06-11 19:22:10.398638+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4c97e17b5cff'
down_revision: Union[str, None] = 'dbb5f4b3a360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default='' — чтобы добавление колонки было безопасным на таблице
    # с уже существующими строками (старые версии получат пустой ключ оригинала).
    op.add_column('document_versions', sa.Column(
        'source_uri', sa.String(length=1024), nullable=False, server_default=''))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'source_uri')
    # ### end Alembic commands ###
